services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        VITE_TARGETED_URL: "/api"
    environment:
      VITE_TARGETED_URL: "/api"
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mongodb://admin:password@mongodb:27017/ICG?authSource=admin"
      JWT_KEY: "supersecretkey"
      APP_PORT: 3000
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ICGmongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - app-network
    depends_on:
      website:
        condition: service_healthy
      dashboard:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - ./website/build:/usr/share/nginx/html/website
      - ./dashboard/dist:/usr/share/nginx/html/dashboard

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
