FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci

ARG VITE_TARGETED_URL
ENV VITE_TARGETED_URL=${VITE_TARGETED_URL}

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

